### PR TITLE
Use whosonfirst downloader

### PR DESCRIPTION
**Pull request by orangejulius**
Instead of having a second script to download data in this repository,
the one in whosonfirst can be reused, since the NPM package is an
indirect dependency of this package.

The README is updated with usage and a link to the whosonfirst readme
for even more configuration options.

### CODE REVIEW

**Comment by orangejulius** [comment]
@trescube Hmmm. but it is an _indirect_ dependency (pelias-wof-admin-lookup depends on pelias-whosonfirst). It worked for me  on NPM 5.4.1 (and whatever my other computer is using, I think NPM 3). What version of NPM did you run it with?

The approach of calling `node node_modules/...` may be flawed. I've heard the NPM team talk about how you shouldn't expect anything within `node_modules` to be in a particular place.

**Comment by trescube** [comment]
```[stephenhess@slumlord pip-service (master $)]$ npm --version
2.15.11```

**Comment by trescube** [comment]
Here are my contents of node_modules:

```
[stephenhess@slumlord pip-service (master $)]$ ll node_modules
total 0
drwxr-xr-x    9 stephenhess  staff    306 Oct 11 10:14 express
drwxr-xr-x   11 stephenhess  staff    374 Oct 11 10:14 jshint
drwxr-xr-x  640 stephenhess  staff  21760 Oct 11 10:14 lodash
drwxr-xr-x    8 stephenhess  staff    272 Oct 11 10:14 morgan
drwxr-xr-x    8 stephenhess  staff    272 Oct 11 10:14 npm-check
drwxr-xr-x   12 stephenhess  staff    408 Oct 11 10:14 pelias-logger
drwxr-xr-x   10 stephenhess  staff    340 Oct 11 10:14 pelias-mock-logger
drwxr-xr-x   16 stephenhess  staff    544 Oct 11 10:14 pelias-wof-admin-lookup
drwxr-xr-x    9 stephenhess  staff    306 Oct 11 10:14 precommit-hook
drwxr-xr-x   13 stephenhess  staff    442 Oct 11 10:14 proxyquire
drwxr-xr-x   10 stephenhess  staff    340 Oct 11 10:14 request
drwxr-xr-x    7 stephenhess  staff    238 Oct 11 10:14 semantic-release
drwxr-xr-x    7 stephenhess  staff    238 Oct 11 10:14 tap-dot
drwxr-xr-x   13 stephenhess  staff    442 Oct 11 10:14 tape
drwxr-xr-x   14 stephenhess  staff    476 Oct 11 10:14 temp
drwxr-xr-x    9 stephenhess  staff    306 Oct 11 10:14 through2
```

**Comment by orangejulius** [comment]
Ah yes that's why. NPM 2 has nested directories. You should seriously upgrade to at least NPM 3. But NPM 5 works pretty well now and is [10X FASTER](https://twitter.com/seldo/status/917891584120709120)

**Comment by orangejulius** [comment]
NPM 2 is beyond old, and we've explicitly upgraded to 3 in all our production environments. We should bump that up higher too honestly.

**Comment by trescube** [comment]
I'll update.  Could you specify the npm version in engines in package.json?

**Comment by orangejulius** [comment]
good idea.

**Comment by trescube** [comment]
Downloader works for me now

**Pull request merged**
